//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.Componente = new HashSet<Componente>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idProjeto { get; set; }
        public string nome { get; set; }
        public string cliente { get; set; }
        public System.DateTime dataIni { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
        public string descricao { get; set; }
        public string area { get; set; }
    
        public virtual Area Area1 { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual ICollection<Componente> Componente { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
