//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto.Dados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Componente
    {
        public Componente()
        {
            this.Keyword = new HashSet<Keyword>();
        }
    
        public int idComponente { get; set; }
        public string nome { get; set; }
        public string usuario { get; set; }
        public Nullable<int> projeto { get; set; }
    
        public virtual Projeto Projeto1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<Keyword> Keyword { get; set; }
    }
}
